Configuratron:
  use_only:
    - sleep-edf
  preload: True
  sfreq: 100
  deep1010:
    return_mask: False

encoder_weights: /dmj/fizmed/jjakubowska/BENDR/weights/encoder.pt
context_weights: /dmj/fizmed/jjakubowska/BENDR/weights/contextualizer.pt

datasets: !include configs/downstream_datasets.yml

