Configuratron:
  use_only:
    - tueg_v1_1
    - bci_iv_2a
  samples: 1500 # = 60 seconds
  sfreq: 250

validation_dataset: bci_iv_2a

augmentation_params:
  upsample_crop: 32
  batch_crop_frac: 0.05

training_params:
  epochs: 40
  validation_interval: 100
  train_log_interval: 100
  batch_size: 128
  warmup_frac: 0.05
  drop_last: False
  

mask_threshold: 0.85
mask_inflation: 1.
mask_pct_max: 0.6

optimizer_params:
  lr: 0.00002
  weight_decay: 0.01
  betas: [0.9, 0.98]

bending_college_args:
  mask_rate: 0.065
  mask_span: 10
  layer_drop: 0.01
  multi_gpu: True
  temp: 0.1
  encoder_grad_frac: 0.1
  num_negatives: 20
  enc_feat_l2: 1.0

datasets:
  tueg_v1_1:
    toplevel: /dmj/fizmed/jjakubowska/TUHdata/tueg_v1_1
    stride: 15000 # = 256 * 60 = 1 min
    picks:
      - eeg
      - EEG
    data_max: 5000
    data_min: -5000

  bci_iv_2a:
    name: "validation"
    toplevel: /dmj/fizmed/jjakubowska/TUHdata/bci_iv_2a
    picks:
      - eeg
      - EEG

    exclude_sessions:
      - "*E*"
    data_max: 5000
    data_min: -5000
