Configuratron:
  use_only:
    - polid
  preload: True
  sfreq: 256
  samples: 15360
  deep1010:
    return_mask: False

encoder_weights: weights/linear-polid-radam-600e-60b.pt
context_weights: weights/contextualizer.pt

datasets: !include configs/sequence_evaluation_datasets.yml

